# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wangxz/project2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wangxz/project2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangxz/project2/CMakeFiles /home/wangxz/project2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangxz/project2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a

# Build rule for target.
a : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 a
.PHONY : a

# fast build rule for target.
a/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/build
.PHONY : a/fast

add.o: add.cpp.o
.PHONY : add.o

# target to build an object file
add.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/add.cpp.o
.PHONY : add.cpp.o

add.i: add.cpp.i
.PHONY : add.i

# target to preprocess a source file
add.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/add.cpp.i
.PHONY : add.cpp.i

add.s: add.cpp.s
.PHONY : add.s

# target to generate assembly for a file
add.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/add.cpp.s
.PHONY : add.cpp.s

cal.o: cal.cpp.o
.PHONY : cal.o

# target to build an object file
cal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/cal.cpp.o
.PHONY : cal.cpp.o

cal.i: cal.cpp.i
.PHONY : cal.i

# target to preprocess a source file
cal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/cal.cpp.i
.PHONY : cal.cpp.i

cal.s: cal.cpp.s
.PHONY : cal.s

# target to generate assembly for a file
cal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/cal.cpp.s
.PHONY : cal.cpp.s

cmp.o: cmp.cpp.o
.PHONY : cmp.o

# target to build an object file
cmp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/cmp.cpp.o
.PHONY : cmp.cpp.o

cmp.i: cmp.cpp.i
.PHONY : cmp.i

# target to preprocess a source file
cmp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/cmp.cpp.i
.PHONY : cmp.cpp.i

cmp.s: cmp.cpp.s
.PHONY : cmp.s

# target to generate assembly for a file
cmp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/cmp.cpp.s
.PHONY : cmp.cpp.s

data.o: data.cpp.o
.PHONY : data.o

# target to build an object file
data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/data.cpp.o
.PHONY : data.cpp.o

data.i: data.cpp.i
.PHONY : data.i

# target to preprocess a source file
data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/data.cpp.i
.PHONY : data.cpp.i

data.s: data.cpp.s
.PHONY : data.s

# target to generate assembly for a file
data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/data.cpp.s
.PHONY : data.cpp.s

div.o: div.cpp.o
.PHONY : div.o

# target to build an object file
div.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/div.cpp.o
.PHONY : div.cpp.o

div.i: div.cpp.i
.PHONY : div.i

# target to preprocess a source file
div.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/div.cpp.i
.PHONY : div.cpp.i

div.s: div.cpp.s
.PHONY : div.s

# target to generate assembly for a file
div.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/div.cpp.s
.PHONY : div.cpp.s

judgefuzhi.o: judgefuzhi.cpp.o
.PHONY : judgefuzhi.o

# target to build an object file
judgefuzhi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/judgefuzhi.cpp.o
.PHONY : judgefuzhi.cpp.o

judgefuzhi.i: judgefuzhi.cpp.i
.PHONY : judgefuzhi.i

# target to preprocess a source file
judgefuzhi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/judgefuzhi.cpp.i
.PHONY : judgefuzhi.cpp.i

judgefuzhi.s: judgefuzhi.cpp.s
.PHONY : judgefuzhi.s

# target to generate assembly for a file
judgefuzhi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/judgefuzhi.cpp.s
.PHONY : judgefuzhi.cpp.s

judgeother.o: judgeother.cpp.o
.PHONY : judgeother.o

# target to build an object file
judgeother.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/judgeother.cpp.o
.PHONY : judgeother.cpp.o

judgeother.i: judgeother.cpp.i
.PHONY : judgeother.i

# target to preprocess a source file
judgeother.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/judgeother.cpp.i
.PHONY : judgeother.cpp.i

judgeother.s: judgeother.cpp.s
.PHONY : judgeother.s

# target to generate assembly for a file
judgeother.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/judgeother.cpp.s
.PHONY : judgeother.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/main.cpp.s
.PHONY : main.cpp.s

min.o: min.cpp.o
.PHONY : min.o

# target to build an object file
min.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/min.cpp.o
.PHONY : min.cpp.o

min.i: min.cpp.i
.PHONY : min.i

# target to preprocess a source file
min.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/min.cpp.i
.PHONY : min.cpp.i

min.s: min.cpp.s
.PHONY : min.s

# target to generate assembly for a file
min.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/min.cpp.s
.PHONY : min.cpp.s

mul.o: mul.cpp.o
.PHONY : mul.o

# target to build an object file
mul.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/mul.cpp.o
.PHONY : mul.cpp.o

mul.i: mul.cpp.i
.PHONY : mul.i

# target to preprocess a source file
mul.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/mul.cpp.i
.PHONY : mul.cpp.i

mul.s: mul.cpp.s
.PHONY : mul.s

# target to generate assembly for a file
mul.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/mul.cpp.s
.PHONY : mul.cpp.s

trans.o: trans.cpp.o
.PHONY : trans.o

# target to build an object file
trans.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/trans.cpp.o
.PHONY : trans.cpp.o

trans.i: trans.cpp.i
.PHONY : trans.i

# target to preprocess a source file
trans.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/trans.cpp.i
.PHONY : trans.cpp.i

trans.s: trans.cpp.s
.PHONY : trans.s

# target to generate assembly for a file
trans.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/trans.cpp.s
.PHONY : trans.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... a"
	@echo "... add.o"
	@echo "... add.i"
	@echo "... add.s"
	@echo "... cal.o"
	@echo "... cal.i"
	@echo "... cal.s"
	@echo "... cmp.o"
	@echo "... cmp.i"
	@echo "... cmp.s"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... div.o"
	@echo "... div.i"
	@echo "... div.s"
	@echo "... judgefuzhi.o"
	@echo "... judgefuzhi.i"
	@echo "... judgefuzhi.s"
	@echo "... judgeother.o"
	@echo "... judgeother.i"
	@echo "... judgeother.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... min.o"
	@echo "... min.i"
	@echo "... min.s"
	@echo "... mul.o"
	@echo "... mul.i"
	@echo "... mul.s"
	@echo "... trans.o"
	@echo "... trans.i"
	@echo "... trans.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

